### ISSUE TITLE
Add ability to use text version of emoji, instead of unicode

### ISSUE THREAD

**Issue by SethGower** [olacin/telescope-gitmoji.nvim#1]
I think it would be a pretty good idea to add the ability to insert the text version of the gitmoji (like `:poop:` instead of :poop:) this way it isn't rendered locally in the terminal, if the user wants. So just store the text version alongside the unicode versions, and have a config option to decide which one to insert when the `Telescope gitmoji` command is called.

**Comment by olacin** [comment]
I like the idea.

By not rendering in the terminal, do you also mean not rendering in the Telescope picker ? 🤔

If you want to contribute, feel free to open a PR, otherwise I'll try to implement this as soon as I get some time for it.

**Comment by SethGower** [comment]
My thought was to render in telescope, but just insert the text. I can try and do it this week.
